services:

  nginx:
    container_name: livewire.nginx
    image: nginx:latest
    build: './nginx/'
    ports:
      - "80:80"
    links:
      - php  
      - mysql
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./..:/var/www/html
    restart: unless-stopped

  php:
    container_name: livewire.php
    image: php:8.1-fpm
    build: './php/'
    expose: 
       - 9000
    links:  
       - mysql
    volumes:
      - ./..:/var/www/html
    restart: unless-stopped

  mysql:
    container_name: livewire.mysql
    build: './mysql/'
    image: mysql:latest
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./..:/var/www/html
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=pwd
    restart: unless-stopped


