services:

  nginx:
    container_name: livewire.nginx
    image: nginx:latest
    build: './nginx/'
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./..:/var/www/html
    restart: unless-stopped

  php:
    user: "${PUID}:${GUID}"
    container_name: livewire.php
    image: php:8.1-fpm
    build: './php/'
    expose: 
       - 9000
    volumes:
      - ./..:/var/www/html
    restart: unless-stopped

  mariadb:
    container_name: livewire.mariadb
    build: './mariadb/'
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    restart: unless-stopped

volumes:
  mariadb_data: